# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NPY.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import random


class Ui_MainWindow(object):
    n_daw = 0
    pobeda = 0
    lyzer = 0

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(90, 160, 101, 31))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(200, 160, 101, 31))
        self.btn_2.setObjectName("btn_2")
        self.btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_3.setGeometry(QtCore.QRect(310, 160, 101, 31))
        self.btn_3.setObjectName("btn_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 100, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(280, 100, 121, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 230, 81, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 230, 71, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(330, 230, 81, 21))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_1.setText(_translate("MainWindow", "Ножницы"))
        self.btn_2.setText(_translate("MainWindow", "Камень"))
        self.btn_3.setText(_translate("MainWindow", "Бумага"))
        self.label.setText(_translate("MainWindow", "Игорёк Мастер"))
        self.label_2.setText(_translate("MainWindow", "Копутор"))
        self.label_3.setText(_translate("MainWindow", "Победы"))
        self.label_4.setText(_translate("MainWindow", "Ничёшка"))
        self.label_5.setText(_translate("MainWindow", "Победка"))

    def add_functions(self):
        self.btn_1.clicked.connect(lambda: self.noz())
        self.btn_2.clicked.connect(lambda: self.kam())
        self.btn_3.clicked.connect(lambda: self.bym())

    def kam(self):
        print("камень")
        ram = random.randint(1, 3)
        self.label.setText("камень")
        if ram == 1:
            self.label_2.setText("камень")
            self.n_daw += 1
        elif ram == 2:
            self.label_2.setText("ножници")
            self.pobeda += 1
        elif ram == 3:
            self.label_2.setText("бумага")
            self.lyzer += 1
        self.label_3.setText(str(self.pobeda))
        self.label_4.setText(str(self.n_daw))
        self.label_5.setText(str(self.lyzer))
        print(self.pobeda, self.n_daw, self.lyzer)

    def noz(self):
        print("Ножницы")
        ram = random.randint(1, 3)
        self.label.setText("Ножницы")
        if ram == 1:
            self.label_2.setText("каммень")
            self.n_daw += 1
        elif ram == 2:
            self.label_2.setText("ножници")
            self.pobeda += 1
        elif ram == 3:
            self.label_2.setText("бумага")
            self.lyzer += 1
        self.label_3.setText(str(self.pobeda))
        self.label_4.setText(str(self.n_daw))
        self.label_5.setText(str(self.lyzer))
        print(self.pobeda, self.n_daw, self.lyzer)

    def bym(self):
        print("Бумага")
        ram = random.randint(1, 3)
        self.label.setText("Бумага")
        if ram == 1:
            self.label_2.setText("каммень")
            self.n_daw += 1
        elif ram == 2:
            self.label_2.setText("ножници")
            self.pobeda += 1
        elif ram == 3:
            self.label_2.setText("бумага")
            self.lyzer += 1
        self.label_3.setText(str(self.pobeda))
        self.label_4.setText(str(self.n_daw))
        self.label_5.setText(str(self.lyzer))
        print(self.pobeda, self.n_daw, self.lyzer)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
